# SPDX-License-Identifier: GPL-2.0-only
ccflags-y += -I$(src)                   # needed for trace events

obj-$(CONFIG_VENDOR_HOOKS) += vendor_hooks.o
obj-$(CONFIG_VENDOR_HOOKS) += cam_heap_hooks.o

